name: yt_digest
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - scrapetube
    - youtube-transcript-api
    - python-dotenv
    - pytest
    - pytest-mock
    - pytest-github-actions-annotate-failures