name: yt_digest
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - scrapetube==2.6.0
    - youtube-transcript-api==1.2.3
    - python-dotenv==1.2.1
    - pytest==9.0.1
    - pytest-mock==3.15.1
    - pytest-github-actions-annotate-failures==0.3.0
    - openai==2.9.0
    - ruff==0.14.8
    - resend==2.19.0
    - markdown==3.10
    - mypy==1.13.0
    - types-Markdown==3.10.0.20251106